"""Generate the loop variants the SHA bench runs (-D SHA_BENCH=2).

    python tools/sha_bench/gen_variants.py [sweep.py]

Writes src/sha_bench_variants.inc (one PL_MINE instance per variant, see
src/pipelined_hw_sha_classic_v2.S for the knobs) and src/sha_bench_variants.h
(the table the bench walks). The sweep file is plain Python calling:

    base(p1=.., d2=.., ...)            set the knob values variants start from
    add(tag, x=None, **overrides)      one variant; tag/x only label the output
                                       iram=1 places it in IRAM like the real
                                       loop, chk=0 drops the checksum (timing
                                       only, the bench will report it as BAD)

Default sweep: sweep_default.py next to this file -- the production schedule,
each delay at its measured threshold, and everything one cycle below it.
"""
import os
import sys

ORDER = ["p1", "d2", "p2", "pl1", "d3", "p3", "pl2", "lpos", "wgap"]
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "src")


def load(sweep_path):
    variants = []
    current = {}

    def base(**kw):
        current.clear()
        current.update(kw)

    def add(tag, x=None, **kw):
        v = dict(current)
        v.update(kw)
        variants.append((tag, x, v))

    with open(sweep_path) as f:
        exec(f.read(), {"base": base, "add": add})
    return variants


def main():
    sweep = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "sweep_default.py")
    variants = load(sweep)
    inc, decl, tab = [], [], []
    for i, (_tag, _x, v) in enumerate(variants):
        name = "plb_%d" % i
        sect = (".iram1.%s" if v.get("iram") else ".text.%s") % name
        args = ", ".join(str(v[k]) for k in ORDER)
        inc.append("    PL_MINE %s, %s, %s, %d" % (name, sect, args, v.get("chk", 1)))
        decl.append('extern "C" uint32_t %s(volatile uint32_t *, pl_ctx_t *);' % name)
        tab.append("    {%s}," % name)
    note = "// Generated by tools/sha_bench/gen_variants.py from %s\n" % os.path.basename(sweep)
    with open(os.path.join(SRC, "sha_bench_variants.inc"), "w") as f:
        f.write(note + "\n".join(inc) + "\n")
    with open(os.path.join(SRC, "sha_bench_variants.h"), "w") as f:
        f.write(note + "\n".join(decl) + "\n"
                "static const struct { uint32_t (*fn)(volatile uint32_t *, pl_ctx_t *); } s_variants[] = {\n"
                + "\n".join(tab) + "\n};\n")
    print(len(variants), "variants")


if __name__ == "__main__":
    main()
